// responseMessage.js
module.exports = {
    NULL_VALUE:"필요한 값이 없습니다.", 
    OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",
    SIGN_UP_SUCCESS: "회원가입 성공", 
    SIGN_UP_FAIL:"회원가입 실패", 
    SIGN_IN_SUCCESS: "로그인 성공", 
    SIGN_IN_FAIL:"로그인 실패", 
    ALREADY_HOST: "존재하는 HOST 입니다.", 
    ALREADY_ADDRESS: "존재하는 ADDRESS 입니다.", 
    NO_ADDRESS: "존재하지않는 ADDRESS 입니다.", 
    MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",
    BLOG_CREATE_SUCCESS: "블로그 작성 성공", 
    BLOG_CREATE_FAIL:"블로그 작성 실패", 
    BLOG_READ_ALL_SUCCESS:"블로그 전체 조회 성공", 
    BLOG_READ_ALL_FAIL:"블로그 전체 조회 실패", 
    BLOG_READ_SUCCESS:"블로그 조회 성공", 
    BLOG_READ_FAIL:"블로그 조회 실패", 
    BLOG_UPDATE_SUCCESS:"블로그 수정 성공", 
    BLOG_UPDATE_FAIL:"블로그 수정 실패", 
    BLOG_DELETE_SUCCESS: "블로그 삭제 성공", 
    BLOG_DELETE_FAIL: "블로그 삭제 실패",
    ALREADY_ID: "존재하는 ID 입니다.", 
    NO_USER: "존재하지 않는 유저 입니다.", 
    NO_BLOG: "존재하는 블로그 입니다.", 
    INTERNAL_SERVER_ERROR: "서버 내부 오류"
}